/*  næ ekki að útfæra :(
const express = require('express');

function catchErrors(fn) {
  return (req, res, next) => fn(req, res, next).catch(next);
}


module.exports = router;
*/
